### PR TITLE
Automatic Hadoop integration on Flink Kubernetes mode

### PR DESCRIPTION
**Pull request by Al-assad**
<br>

### What problem does this PR solve?

**Problem Summary:**

There are currently 3 main ways to implement hadoop integration with Flink-Native-K8s:

* Provide Hadoop lib and configuration files in the user custom Flink base image.
* Specify the initContainer spec that provides the Hadoop lib and configuration files in the pod template.
* Specify the PVC spec that provides the Hadoop lib and configuration files in the pod template.

Since the first 2 ways have additional requirements and intrusions on the user's kubernetes cluster resources, this PR is implemented in the first way.
  
<br>

### How it Works:

The internal process for submitting Flink K8s-Application mode job with Hadoop Integration is as follow:

iShot2021-11-11 14.08.22

*excalidraw source file: https://drive.google.com/file/d/1HPZaL9GFlbKUOd90mdhyLF0z9hm2p7em/view?usp=sharing*

1. **Build Flink Job Jar**

   Both the user's Flink Sql and custom code will be built as a shaded jar.

2. **Build Flink Docker Image**

   There are 3 key resources:

   * The Flink job shaded jar that offered main class will be copied to the`$FLINK_HOME/usrlib/` in the image.
   * The Hadoop lib (such as `flink-shaded-hadoop-2-uber-2.7.5-10.0.jar`, `flink-sql-connector-hive-3.1.2_2.11-1.13.0.jar`) will be copied to the `$FLINK_HOME/lib/` .
   * The Hadoop Configuration files from system environment variables (`HADOOP_HOME`, `HADOOP_CONF_DIR`, `HIVE_CONF_DIR`) such as `core-site.xml`,`hdfs-site.xml`, `hive-site.xml` will be copied to the `/opt/hadoop-conf` and `/opt/hive-conf`.

   The build steps in dockerfile have been reorganized as follows **to better use the docker image cache for the duplicate layer**:

   ```dockerfile
   FROM ${flinkBaseImage}
   RUN mkdir -p $FLINK_HOME/usrlib
   
   COPY ${hadoopConfDir} /opt/hadoop-conf
   ENV HADOOP_CONF_DIR /opt/hadoop-conf
   
   COPY ${hiveConfDir} /opt/hive-conf
   ENV HIVE_CONF_DIR /opt/hive-conf
   
   COPY ${extraFlinkLib} $FLINK_HOME/lib/
   COPY ${userFatJar} $FLINK_HOME/usrlib/${userFatJar}
   ```

3. **Push Flink Docker to Remote Register Repository**

4. **Submit Flink Job to Kubernetes Cluster with Built Image**

   During the Flink job submission phase, an auto-generated or auto-merge pod template configuration will be used to resolve the host mapping in the hadoop configuraton file. This pod template contains an additional `HostAlias Spec` node which are extracted from the system host file,  users can of course modify this HostAlias themselves.

<br>

###  Use case

The following example demonstrates submitting a Flink SQL job containing Hive data processing.

1. **Add a New Flink Job**
image-20211111145835759

2. **Fill in the basic Flink K8s Application mode configuration**

image-20211111150125801

The sql used for the demo is as follows:

```sql
create catalog myhive with (
    'type' = 'hive',
    'hive-conf-dir' = '/opt/hive-conf'
);

create temporary table heros (
    `name` string,
    `power` string,
    `age` int
) with (
    'connector' = 'faker',
    'number-of-rows' = '1000',
    'rows-per-second' = '1000',
    'fields.name.expression' = '#{superhero.name}',
    'fields.power.expression' = '#{superhero.power}',
    'fields.power.null-rate' = '0.05',
    'fields.age.expression' = '#{number.numberbetween ''0'',''1000''}'
);

insert into myhive.test.heros select * from heros;
```

3. **Upload hadoop dependencies**

image-20211111150428539

The dependencies used in the demo are as follow:

* flink-faker-0.3.0.jar
* flink-shaded-hadoop-2-uber-2.7.5-10.0.jar
* flink-sql-connector-hive-3.1.2_2.11-1.13.0.jar

**`Tip`: You can quickly select or search for the relevant dependencies directory in the upload history**

* *Quick selection of historical dependencies*

	image-20211111150856169

* *Quick search of historical dependencies by keyword*

​	image-20211111151158529

4. **Enable `Use System Hadoop Conf`**

image-20211111151811077

Tip: You can click the `view`	button to browse the hadoop config content that will be used.

image-20211111151828832

5. **Configure HostAlias in Podtemplate**

You can use the `Host Alias` tool button to quickly generate the relevant spec configuration.

image-20211111152041400

The HostAlias tool panel supports entering host mappings directly, or quickly selecting them directly from the system host file.

image-20211111152252395

Then click the submit button and the relevant podtemplate configuration will be generated automatically.

image-20211111152520479

`Tip`: You can quickly select a historical podtemplate configuration by clicking the `History` button

image-20211111153023071

6. **Finally, let's submit and run this job.**

image-20211111152659495

<br>

#### 1. Quick selection of historical configurations on the Add/Edit page

​	A quick selection of historical configurations is provided to facilitate the user to quickly configure a Flink job that contains:	

* Kubernetes Namespace
* Flink Base Docker Image
* Flink Session Id
* Upload Jars
* PodTemplate

These features have been demonstrated in the Use Case above.

#### 2. [docker-java](https://github.com/docker-java/docker-java) improvements with callback listener support.

Implement docker-java callbck listener feature by a hack way. This feature allows to listen the actual progress details of the `docker pull /push api` and the actual build step progress of the `docker build image api`.

The main purpose is to provide more granular build progress information **for the subsequent streamx flink-k8s job build/run separation**.

**The relevant code**: https://github.com/Al-assad/streamx/tree/k8s-hadoop-integration/streamx-plugin/streamx-flink-packer/src/main/java/com/github/dockerjava

```scala
// use case: watch the build image step
usingDockerClient {
  dockerClient =>
  	val buildImageCmd = dockerClient.buildImageCmd()
  		.withBaseDirectory(baseDirectory)
  		.withDockerfile(dockerfile)
  		.withTags(Sets.newHashSet(tagName))
  	val buildCmdCallback = buildImageCmd.asInstanceOf[HackBuildImageCmd].start(
            watchDockerBuildStep(
               buildStep =>
        	   logInfo(s"current build step: ${buildStep}")
     ))
    val imageId = buildCmdCallback.awaitImageId
}

// use case: watch the pull progress detail
usingDockerClient {
  dockerClient =>
  	val pullImageCmd = dockerClient.pullImageCmd(flinkImageTag)
  	pullImageCmd.asInstanceOf[HackPullImageCmd].start(
           watchDockerPullProcess(
             progress =>
        	logInfo(s"id=${progress.getKey} => status=${progress.getValue.getStatus}, currentPg=${progress.getValue.getProgressDetail.getCurrent}")
     ))
  	.awaitCompletion()
}

// use case: watch the push progress detail
 usingDockerClient {
   dockerClient =>
       val pushCmd: PushImageCmd = dockerClient.pushImageCmd(tagName).withAuthConfig(authConf.toDockerAuthConf)
       pushCmd.start(
            watchDockerPushProcess(
                progress =>
        	    logInfo(s"id=${progress.getKey} => status=${progress.getValue.getStatus}, currentPg=${progress.getValue.getProgressDetail.getCurrent}")
     )
   ).awaitCompletion
   
}
```

<br>

<br>

### CODE REVIEW

**Comment by wolfboys** [comment]
Good job! thank  u  for  u  hard  work👏

**Comment by Al-assad** [comment]
All the works have been finished, please take a look. @wolfboys

**Comment by wolfboys** [comment]
good job! 👍👍👍 👏

**Comment by Al-assad** [comment]
@wolfboys Based on your suggestion, here is the link to the code optimization commit: https://github.com/streamxhub/streamx/pull/401/commits/5b10a200bcb8b4774d3f465cdea8769a1717becf

**Comment by Al-assad** [comment]
> 

I think this works because there are two tool Utils for getting the system Hadoop configuration in StreamX,`HadoopUtil` throws an exception directly when the relevant configuration is not obtained, which is an exception blocking method, and `HadoopConfigUtil` which is returned as a safe empty string.
see: https://github.com/streamxhub/streamx/blob/main/streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala#L89

**Comment by Al-assad** [comment]
> Considering that this is a public method, if can't get it, return empty string, I think this place need to discussion. Although it can effectively avoid NullPointException.

I think this works because there are two tool Utils for getting the system Hadoop configuration in StreamX,HadoopUtil throws an exception directly when the relevant configuration is not obtained, which is an exception blocking method, and HadoopConfigUtil which is returned as a safe empty string.
see: https://github.com/streamxhub/streamx/blob/main/streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala#L89

**Comment by wolfboys** [comment]
> > Considering that this is a public method, if can't get it, return empty string, I think this place need to discussion. Although it can effectively avoid NullPointException.
> 
> I think this works because there are two tool Utils for getting the system Hadoop configuration in StreamX,HadoopUtil throws an exception directly when the relevant configuration is not obtained, which is an exception blocking method, and HadoopConfigUtil which is returned as a safe empty string. see: https://github.com/streamxhub/streamx/blob/main/streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala#L89

i think, if can't get it return null, else return result. would it be better ? i think this method is not customized for someone, can be used everywhere,  HadoopUtils is also use this method later.

**Comment by Al-assad** [comment]
> 



> > > Considering that this is a public method, if can't get it, return empty string, I think this place need to discussion. Although it can effectively avoid NullPointException.
> > 
> > 
> > I think this works because there are two tool Utils for getting the system Hadoop configuration in StreamX,HadoopUtil throws an exception directly when the relevant configuration is not obtained, which is an exception blocking method, and HadoopConfigUtil which is returned as a safe empty string. see: https://github.com/streamxhub/streamx/blob/main/streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala#L89
> 
> i think, if can't get it return null, else return result. would it be better ? i think this method is not customized for someone, can be used everywhere, HadoopUtils is also use this method later.

or return a `Option`, that is more null-safe and more in line with the Scala and Java API design.🙂 The caller can distinguish between calling an exception or actually getting a "" string with `getOrElse` or `orElse`. 
Just like that:
```
def getSystemHadoopConfDir: Option[String] = 
     Try(FileUtils.getPathFromEnv("HADOOP_CONF_DIR"))
       .recover { case _ => FileUtils.resolvePath(FileUtils.getPathFromEnv("HADOOP_HOME"), "/etc/hadoop") }
       .toOption
```

**Comment by wolfboys** [comment]
> 




> > 
> 
> > > > Considering that this is a public method, if can't get it, return empty string, I think this place need to discussion. Although it can effectively avoid NullPointException.
> > > 
> > > 
> > > I think this works because there are two tool Utils for getting the system Hadoop configuration in StreamX,HadoopUtil throws an exception directly when the relevant configuration is not obtained, which is an exception blocking method, and HadoopConfigUtil which is returned as a safe empty string. see: https://github.com/streamxhub/streamx/blob/main/streamx-common/src/main/scala/com/streamxhub/streamx/common/util/HadoopUtils.scala#L89
> > 
> > 
> > i think, if can't get it return null, else return result. would it be better ? i think this method is not customized for someone, can be used everywhere, HadoopUtils is also use this method later.
> 
> or return a `Option` ? That is more null-safe and more in line with the Scala and Java API design.🙂 The caller can distinguish between calling an exception or actually getting a "" string with `getOrElse` or `orElse`. Just like that:
> 
> ```
> def getSystemHadoopConfDir: Option[String] = 
>      Try(FileUtils.getPathFromEnv("HADOOP_CONF_DIR"))
>        .recover { case _ => FileUtils.resolvePath(FileUtils.getPathFromEnv("HADOOP_HOME"), "/etc/hadoop") }
>        .toOption
> ```

return a Option, good idea.i agree with you👍

**Comment by Al-assad** [comment]
@wolfboys PTAL https://github.com/streamxhub/streamx/pull/401/commits/85661ed5125befc9165884809dfc790e1baa8276

**Comment by wolfboys** [comment]
> @wolfboys PTAL [85661ed](https://github.com/streamxhub/streamx/commit/85661ed5125befc9165884809dfc790e1baa8276)

good job. LGTM.

**Comment by wolfboys** [comment]
@Al-assad Hi Al-assad, Thanks for your contribution.

It seems there are 2 main problems with this PR:

1.  log prefix without : "[]", because log prefix [streamx] is already configured in logback.xml.
2. FileUtils some method(copy,copyDir),need to be tested, I'm afraid have some bug.

**Comment by Al-assad** [comment]
> @Al-assad Hi Al-assad, Thanks for your contribution.
> 
> It seems there are 2 main problems with this PR:
> 
> 1. log prefix without : "[]", because log prefix [streamx] is already configured in logback.xml.
> 2. FileUtils some method(copy,copyDir),need to be tested, I'm afraid have some bug.

i will add some unit tests for FileUtils later.

**Comment by Al-assad** [comment]
@wolfboys Hi, When I wrote the complete unit test for `LfsOperator`, I found  there are still a lot of leftover bugs, so I think this PR can be merged to main first, and I will submit a new PR about the `LfsOperator` bug fix and relevant unit tests.

**Comment by wolfboys** [comment]
LGTM.  Thanks for your contribution.

**Pull request merged**
